version: '3'

tasks:
  install:
    desc: Install dependencies
    cmds:
    - bun install

  ci:
    cmds:
    - bun install --frozen-lockfile

  test:
    desc: Run tests
    cmds:
    - bun test

  dev:
    desc: Run tests in watch mode
    cmds:
    - bun test --watch

  check:
    desc: Check for issues
    cmds:
    - bunx --bun tsc
    - task: prettier
      vars:
        PRETTIER_ARGS: --check

  fix:
    desc: Fix issues
    cmds:
    - task: prettier
      vars:
        PRETTIER_ARGS: --write


  prettier:
    cmds:
    - bunx --bun prettier "./**/*.{html,ts,tsx,json,js,jsx,cjs,css}" {{.PRETTIER_ARGS}}

  build:
    desc: Build the distributable web app
    cmds:
    - mkdir -p dist temp
    - rm -rf dist/*
    - cp src/index.html dist/index.html
    - bun build ./src/main.ts --outfile=dist/main.js --minify
    - bun build ./src/code.ts --outfile=temp/code.gs --minify
    - sed -i -e '1s/^/var calc=(function(){ /' temp/code.gs
    - sed -i -e 's/;window\.__calc=/;return /' temp/code.gs
    - cp src/code.gs dist/appscript.txt
    - cat temp/code.gs >> dist/appscript.txt
    - echo '})()' >> dist/appscript.txt
    - echo '//! https://github.com/Pistonite/addtime' > dist/time.ts
    - echo '' >> dist/time.ts
    - cat src/time.ts >> dist/time.ts

  serve:
    desc: Serve /dist
    cmds:
    - bunx --bun serve dist
